import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { deleteVaultItem, downloadVaultItem, listVault, uploadVaultFile } from '../../services/vaultService';

const styles = { page: { minHeight: '100vh', padding: '32px', background: '#f8fafc', color: '#0f172a' }, card: { padding: '18px', borderRadius: '14px', background: '#fff', boxShadow: '0 5px 20px rgba(15,23,42,.06)' }, input: { padding: '10px', border: '1px solid #cbd5e1', borderRadius: '8px', width: '100%', boxSizing: 'border-box', margin: '5px 0 12px' } };

export default function VaultPage() {
  const [items, setItems] = useState([]); const [file, setFile] = useState(null); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [progress, setProgress] = useState(0); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function refresh() { try { const data = await listVault(); setItems(data.items || []); } catch (e) { setError(e.message); } }
  useEffect(() => { refresh(); }, []);
  async function upload(event) { event.preventDefault(); setError(''); setMessage(''); if (!file || file.type !== 'application/pdf' || file.size > 20 * 1024 * 1024) { setError('Choose a PDF file no larger than 20 MB.'); return; } try { await uploadVaultFile({ file, title, description, onProgress: setProgress }); setMessage('File encrypted and added to the vault.'); setFile(null); setTitle(''); setDescription(''); await refresh(); } catch (e) { setError(e.message); } }
  async function remove(id) { if (!window.confirm('Delete this encrypted vault item permanently?')) return; try { await deleteVaultItem(id); await refresh(); } catch (e) { setError(e.message); } }
  return <main style={styles.page}><div style={{ maxWidth: '1000px', margin: '0 auto' }}><h1>Secure Vault</h1><p>Documents are encrypted with AES-256-GCM before vault storage.</p><section style={{ ...styles.card, marginBottom: '20px' }}><h2>Add encrypted document</h2><form onSubmit={upload}><label>PDF file<input style={styles.input} type="file" accept="application/pdf,.pdf" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><label>Title<input style={styles.input} value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Description<textarea style={styles.input} value={description} onChange={(e) => setDescription(e.target.value)} /></label>{progress > 0 && <p>Upload progress: {progress}%</p>}<button type="submit">Encrypt and store</button></form></section>{error && <p style={{ color: '#b91c1c' }}>{error}</p>}{message && <p style={{ color: '#15803d' }}>{message}</p>}<div style={{ display: 'grid', gap: '14px' }}>{items.length === 0 && <div style={styles.card}>No Encrypted Documents Yet</div>}{items.map((item) => <article key={item.id} style={styles.card}><h2>{item.title}</h2><p>{item.originalName} · {item.originalSize} bytes</p><p>Algorithm: {item.encryptionAlgorithm} · Created: {item.createdAt}</p><Link to={`/vault/${item.id}`}>View details</Link>{' '}<button type="button" onClick={() => downloadVaultItem(item.id, item.originalName)}>Download</button>{' '}<button type="button" onClick={() => remove(item.id)}>Delete</button></article>)}</div></div></main>;
}
