import { useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useReducedMotion } from 'framer-motion';
import { useTheme } from '../../context/ThemeContext';
import SectionCard from '../ui/SectionCard';
import '../../styles/dashboard-analytics.css';

const colors = ['#7863e6', '#24a991', '#5095e8', '#d59533', '#cf718d', '#8490a4'];
const tooltip = { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, color: 'var(--text)', fontSize: 12 };
const dateLabel = (date) => new Date(`${date}T00:00:00Z`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', timeZone: 'UTC' });
const label = (name) => String(name).replaceAll('_', ' ');
function EmptyChart({ children = 'Your data will appear here as you use your workspace.' }) { return <div className="analytics-empty"><span>Nothing to chart yet</span><p>{children}</p></div>; }
function Breakdown({ rows, animate }) {
	if (!rows.length) return <EmptyChart/>;
	return <><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={62} outerRadius={87} paddingAngle={rows.length > 1 ? 3 : 0} stroke="none" isAnimationActive={animate} animationDuration={250}>{rows.map((row, i) => <Cell key={row.name} fill={colors[i % colors.length]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><ul className="analytics-legend">{rows.map((row, i) => <li key={row.name}><i style={{ background: colors[i % colors.length] }}/><span>{label(row.name)}</span><strong>{row.value}</strong></li>)}</ul></>;
}
export default function DashboardAnalytics({ summary }) {
	const [range, setRange] = useState(30);
	const { motionEnabled } = useTheme();
	const reduced = useReducedMotion();
	const animate = motionEnabled && !reduced;
	const analytics = summary.analytics;
	if (!analytics) return <SectionCard title="Analytics unavailable"><p>Refresh the page after restarting the server to load the updated analytics.</p></SectionCard>;
	const daily = analytics.daily.slice(-range);
	const totals = daily.reduce((acc, day) => { for (const key of Object.keys(acc)) acc[key] += day[key]; return acc; }, { assets: 0, documents: 0, verifications: 0, earnings: 0, spending: 0 });
	return <section className="dashboard-analytics" aria-label="Workspace analytics">
		<header className="analytics-heading"><div><span>WORKSPACE INTELLIGENCE</span><h2>Your activity, in perspective.</h2><p>Daily trends in UTC. Inventory charts show your current collection.</p></div><div className="analytics-range" role="group" aria-label="Chart time range">{[7, 30].map((days) => <button type="button" key={days} aria-pressed={range === days} onClick={() => setRange(days)}>Last {days} days</button>)}</div></header>
		<div className="analytics-kpis" aria-live="polite">{[['Files created', totals.assets + totals.documents, 'Currently owned images + documents'], ['Verification runs', totals.verifications, `Reports created in ${range} days`], ['Seller earnings', `${totals.earnings.toLocaleString()} cr`, 'Completed sales, after platform fees'], ['Purchase spending', `${totals.spending.toLocaleString()} cr`, 'Completed marketplace purchases']].map(([title, value, note]) => <article key={title}><span>{title}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
		<div className="analytics-grid">
			<SectionCard title="Creation & verification activity" description={`All records across the last ${range} days, not just recent events.`} className="analytics-wide">{totals.assets + totals.documents + totals.verifications ? <ResponsiveContainer width="100%" height={285}><AreaChart data={daily} margin={{ top: 15, right: 10, bottom: 0, left: -20 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={35} tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={dateLabel}/><Legend wrapperStyle={{ fontSize: 12 }}/>{[['assets', 'Images', colors[0]], ['documents', 'Documents', colors[1]], ['verifications', 'Verifications', colors[2]]].map(([key, name, color]) => <Area key={key} dataKey={key} name={name} type="monotone" stroke={color} fill={color} fillOpacity={.08} strokeWidth={2} isAnimationActive={animate} animationDuration={250}/>)}</AreaChart></ResponsiveContainer> : <EmptyChart>Upload a file or run a verification to start your activity timeline.</EmptyChart>}<p className="analytics-footnote">Image and document counts use creation dates of files you currently own.</p></SectionCard>
			<SectionCard title="Collection mix" description={`${summary.totalAssets + summary.totalDocuments} files in your libraries`}><Breakdown rows={[{ name: 'Image assets', value: summary.totalAssets }, { name: 'Documents', value: summary.totalDocuments }].filter((row) => row.value)} animate={animate}/></SectionCard>
			<SectionCard title="Document OCR status" description="Current extraction results across your documents"><Breakdown rows={analytics.ocr} animate={animate}/></SectionCard>
			<SectionCard title="Asset categories" description="Current asset count by category">{analytics.categories.length ? <ResponsiveContainer width="100%" height={280}><BarChart data={analytics.categories} layout="vertical" margin={{ left: 0, right: 16 }}><CartesianGrid stroke="var(--border)" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><YAxis type="category" dataKey="name" width={95} tick={{ fill: 'var(--text-muted)', fontSize: 10 }} tickFormatter={(name) => name.length > 14 ? `${name.slice(0, 13)}…` : name}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" name="Assets" fill={colors[0]} radius={[0, 5, 5, 0]} maxBarSize={24} isAnimationActive={animate} animationDuration={250}/></BarChart></ResponsiveContainer> : <EmptyChart/>}</SectionCard>
			<SectionCard title="Verification outcomes" description="All saved report statuses"><Breakdown rows={analytics.verification} animate={animate}/></SectionCard>
			<SectionCard title="Marketplace cash flow" description={`Credits earned and spent over the last ${range} days`} className="analytics-wide">{totals.earnings + totals.spending ? <ResponsiveContainer width="100%" height={260}><BarChart data={daily} margin={{ left: -10, right: 10 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={35} tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><YAxis tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><Tooltip contentStyle={tooltip} labelFormatter={dateLabel} formatter={(value) => `${value.toLocaleString()} cr`}/><Legend wrapperStyle={{ fontSize: 12 }}/><Bar name="Seller earnings" dataKey="earnings" fill={colors[1]} radius={[4, 4, 0, 0]} isAnimationActive={animate} animationDuration={250}/><Bar name="Purchases" dataKey="spending" fill={colors[0]} radius={[4, 4, 0, 0]} isAnimationActive={animate} animationDuration={250}/></BarChart></ResponsiveContainer> : <EmptyChart>Completed purchases and sales will appear here.</EmptyChart>}</SectionCard>
			<SectionCard title="Vault organization" description="Assets assigned to at least one of your vaults"><div className="analytics-coverage"><strong>{summary.totalAssets ? Math.round(summary.totalOrganizedAssets / summary.totalAssets * 100) : 0}<small>%</small></strong><progress aria-label="Assets organized in vaults" max={Math.max(1, summary.totalAssets)} value={summary.totalOrganizedAssets}/><p>{summary.totalOrganizedAssets} of {summary.totalAssets} assets organized</p><span>{summary.totalVaults} vaults · {summary.activeListings} active listings</span></div></SectionCard>
		</div>
	</section>;
}
