import { Check, Save, Settings2, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';

import { AdminError, AdminLoading } from '../../components/admin/AdminDataState';
import AdminPageHeader from '../../components/admin/AdminPageHeader';
import { adminService } from '../../services/adminService';

export default function AdminSettingsPage() {
	const [form, setForm] = useState({ commissionPercentage:'', minimumListingPrice:'' }); const [loading, setLoading] = useState(true); const [saved, setSaved] = useState(false); const [error, setError] = useState('');
	async function load() { setLoading(true); setError(''); try { const settings = await adminService.getSettings(); setForm({ commissionPercentage:(Number(settings.marketplace_commission_rate?.value || 0)*100).toFixed(2), minimumListingPrice:String(Number(settings.minimum_listing_price?.value || 1)) }); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }
	useEffect(() => { load(); }, []);
	async function save(event) { event.preventDefault(); setError(''); try { await adminService.updateMarketplaceSettings({ commissionPercentage:Number(form.commissionPercentage), minimumListingPrice:Number(form.minimumListingPrice) }); setSaved(true); window.setTimeout(() => setSaved(false),2200); } catch (saveError) { setError(saveError.message); } }
	const header = <AdminPageHeader eyebrow="System" title="Platform settings" description="Configuration persisted by the backend and enforced in marketplace transactions." showRange={false}/>;
	if (loading) return <>{header}<AdminLoading label="Loading platform settings"/></>; if (error && !form.commissionPercentage) return <>{header}<AdminError message={error} onRetry={load}/></>;
	return <>{header}{error ? <div className="error-banner">{error}</div> : null}<div className="admin-settings-grid"><form className="admin-card admin-settings-form" onSubmit={save}><header><span><Settings2 size={18}/></span><div><h2>Marketplace economics</h2><p>Both values are read by the purchase and listing workflows.</p></div></header><div className="admin-settings-fields"><label><span>Marketplace commission</span><p>Percentage retained atomically from each successful sale.</p><div><input type="number" min="0" max="20" step="0.1" value={form.commissionPercentage} onChange={(event) => setForm({ ...form, commissionPercentage:event.target.value })}/><b>%</b></div></label><label><span>Minimum listing price</span><p>New and updated listings below this value are rejected by the API.</p><div><b>$</b><input type="number" min="0.01" max="1000000000" step="0.01" value={form.minimumListingPrice} onChange={(event) => setForm({ ...form, minimumListingPrice:event.target.value })}/></div></label></div><footer><button className="admin-button" type="submit">{saved ? <Check size={15}/> : <Save size={15}/>} {saved ? 'Changes saved' : 'Save settings'}</button></footer></form><section className="admin-card admin-settings-form"><header><span><ShieldAlert size={18}/></span><div><h2>Security policy status</h2><p>Unavailable controls are not presented as enabled settings.</p></div></header><div className="admin-settings-fields"><div className="info-banner">MFA policy, session timeout, payout holds, export auditing, and retention controls do not yet have enforcement mechanisms in this application. Configure them only after their backend services and schema are implemented.</div></div></section></div></>;
}
