import { AlertTriangle, ArrowRight, BadgeDollarSign, CheckCircle2, CircleDollarSign, FileCheck2, Images, ShoppingBag, UsersRound } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';

import ActivityTimeline from '../../components/admin/ActivityTimeline';
import AdminPageHeader from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';
import TransactionTable from '../../components/admin/TransactionTable';
import { dashboardTrend, revenueSources, securityEvents, transactions } from '../../admin/adminData';
import { useAuth } from '../../context/AuthContext';
import { adminService } from '../../services/adminService';

export default function AdminDashboardPage() {
	const { user } = useAuth();
	const [overview, setOverview] = useState(null);
	useEffect(() => { adminService.getOverview().then(setOverview).catch(() => {}); }, []);
	const name = user?.fullName?.split(' ')[0] || 'Admin';
	const hour = new Date().getHours();
	const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
	return <>
		<AdminPageHeader eyebrow="Platform overview" title={`${greeting}, ${name}`} description="Here’s what’s happening across VaultChain today." exportName="vaultchain-platform-overview"/>
		<div className="admin-stats-grid is-five"><StatCard label="Total users" value={overview ? Number(overview.totalUsers).toLocaleString() : '24,532'} change="12.5%" detail="Compared to last month" icon={UsersRound} tone="purple"/><StatCard label="Registered assets" value={overview ? Number(overview.totalAssets).toLocaleString() : '185,420'} change="8.2%" detail="12,418 added this month" icon={Images} tone="blue" delay={.04}/><StatCard label="Verified assets" value={overview ? Number(overview.verifiedAssets).toLocaleString() : '172,890'} change="4.8%" detail="Verification coverage" icon={FileCheck2} tone="green" delay={.08}/><StatCard label="Marketplace revenue" value={overview ? `$${Number(overview.marketplaceRevenue).toLocaleString()}` : '$124,500'} change="18.4%" detail="Commission earned" icon={CircleDollarSign} tone="amber" inverse delay={.12}/><StatCard label="Transactions" value={overview ? Number(overview.totalTransactions).toLocaleString() : '8,920'} change="9.7%" detail="Successful sales" icon={ShoppingBag} tone="cyan" delay={.16}/></div>

		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Revenue & marketplace growth" description="Gross commission revenue over the last 6 months" action={<div className="admin-chart-legend"><span><i/>Revenue</span><Link to="/admin/revenue">View report <ArrowRight size={13}/></Link></div>}><div className="admin-chart-total"><strong>$541,000</strong><span><b>+18.4%</b> vs previous period</span></div><ResponsiveContainer width="100%" height={285}><AreaChart data={dashboardTrend} margin={{ top: 10, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="dashboardRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--admin-accent)" stopOpacity={.28}/><stop offset="1" stopColor="var(--admin-accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }} dy={8}/><YAxis tickFormatter={(value) => `$${value / 1000}K`} axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><Tooltip formatter={(value) => `$${value.toLocaleString()}`} contentStyle={{ background: 'var(--surface-raised)', border: '1px solid var(--border)', borderRadius: 10 }}/><Area type="monotone" dataKey="revenue" stroke="var(--admin-accent)" strokeWidth={2.5} fill="url(#dashboardRevenue)"/></AreaChart></ResponsiveContainer></AnalyticsCard>
		<AnalyticsCard title="Revenue sources" description="Current period distribution"><div className="admin-donut"><ResponsiveContainer width="100%" height={215}><PieChart><Pie data={revenueSources} dataKey="value" innerRadius={63} outerRadius={83} paddingAngle={3} stroke="none">{revenueSources.map((item) => <Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{ background: 'var(--surface-raised)', border: '1px solid var(--border)', borderRadius: 10 }}/></PieChart></ResponsiveContainer><div><strong>100%</strong><span>Revenue</span></div></div><div className="admin-source-list">{revenueSources.map((item) => <div key={item.name}><span><i style={{ background: item.color }}/>{item.name}</span><strong>{item.value}%</strong></div>)}</div></AnalyticsCard>
		</div>

		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Transaction volume" description="Completed marketplace sales"><ResponsiveContainer width="100%" height={250}><BarChart data={dashboardTrend}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }}/><Tooltip cursor={{ fill: 'var(--surface-hover)' }} contentStyle={{ background: 'var(--surface-raised)', border: '1px solid var(--border)', borderRadius: 10 }}/><Bar dataKey="transactions" fill="var(--admin-accent)" radius={[5,5,0,0]} maxBarSize={38}/></BarChart></ResponsiveContainer></AnalyticsCard><AnalyticsCard title="Platform health" description="Live system indicators"><div className="admin-health-score"><div><strong>99.98%</strong><span>Uptime</span></div><CheckCircle2 size={23}/></div><div className="admin-health-list"><div><span>API response time</span><strong>124 ms</strong></div><div><span>Verification queue</span><strong>18 assets</strong></div><div><span>Payment success</span><strong>99.4%</strong></div><div><span>Open disputes</span><strong className="is-warning">7 cases</strong></div></div><Link className="admin-inline-link" to="/admin/security">Open system monitor <ArrowRight size={13}/></Link></AnalyticsCard></div>

		<AnalyticsCard title="Recent transactions" description="Latest marketplace commission activity" action={<Link className="admin-inline-link" to="/admin/transactions">View all transactions <ArrowRight size={13}/></Link>}><TransactionTable rows={transactions.slice(0, 4)} compact/></AnalyticsCard>
		<div className="admin-dashboard-grid admin-bottom-grid"><AnalyticsCard className="is-wide" title="Security activity" description="Events requiring administrative awareness" action={<span className="admin-alert-count"><AlertTriangle size={13}/> 2 need attention</span>}><ActivityTimeline items={securityEvents.slice(0, 3)}/></AnalyticsCard><section className="admin-commission-card"><header><span><BadgeDollarSign size={19}/></span><b>Primary revenue model</b></header><h2>Marketplace transaction commission</h2><p>VaultChain automatically retains a 5% platform fee from every successful sale.</p><div className="admin-commission-flow"><div><small>Buyer pays</small><strong>$1,000</strong></div><ArrowRight size={16}/><div className="is-accent"><small>VaultChain fee</small><strong>$50</strong></div><ArrowRight size={16}/><div><small>Seller receives</small><strong>$950</strong></div></div><Link to="/admin/revenue">Explore revenue analytics <ArrowRight size={13}/></Link></section></div>
	</>;
}
