import { Activity, AlertTriangle, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react';

import { securityEvents } from '../../admin/adminData';
import ActivityTimeline from '../../components/admin/ActivityTimeline';
import AdminPageHeader from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';

export default function AdminSecurityPage() {
	return <><AdminPageHeader eyebrow="Intelligence" title="Security monitoring" description="Observe authentication, permissions, threat signals, and platform resilience." exportName="vaultchain-security"/><div className="admin-stats-grid"><StatCard label="Security score" value="96 / 100" change="2.1%" detail="Strong security posture" icon={ShieldCheck} tone="green"/><StatCard label="Blocked threats" value="148" change="-8.4%" detail="Last 30 days" icon={LockKeyhole} tone="red"/><StatCard label="Active sessions" value="19,482" change="7.6%" detail="Across 84 countries" icon={Activity} tone="blue"/><StatCard label="Risky accounts" value="38" change="-5.2%" detail="Queued for review" icon={AlertTriangle} tone="amber"/></div><div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Recent security events" description="Authentication, verification, and access-control signals"><ActivityTimeline items={securityEvents}/></AnalyticsCard><AnalyticsCard title="Security controls" description="Protection layer status"><div className="admin-control-list"><article><span><KeyRound size={16}/></span><div><strong>Multi-factor authentication</strong><p>Required for administrators</p></div><b>Enforced</b></article><article><span><ShieldCheck size={16}/></span><div><strong>Threat detection</strong><p>Behavioral monitoring</p></div><b>Active</b></article><article><span><LockKeyhole size={16}/></span><div><strong>Data encryption</strong><p>AES-256 at rest</p></div><b>Active</b></article><article><span><Activity size={16}/></span><div><strong>Audit logging</strong><p>365-day retention</p></div><b>Active</b></article></div></AnalyticsCard></div><section className="admin-card admin-risk-table"><header><div><h2>Sessions requiring attention</h2><p>Risk-scored sessions detected in the last 24 hours</p></div><button className="admin-button is-secondary" type="button">Review all sessions</button></header><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Location</th><th>IP address</th><th>Device</th><th>Risk score</th><th>Last active</th><th/></tr></thead><tbody><tr><td><strong>karim@exposure.art</strong></td><td>Frankfurt, DE</td><td><code>45.142.21.88</code></td><td>Chrome · Windows</td><td><span className="admin-status is-danger">High · 92</span></td><td>2 min ago</td><td><button className="admin-button is-quiet">Revoke</button></td></tr><tr><td><strong>user2381@email.com</strong></td><td>Ashburn, US</td><td><code>34.201.81.20</code></td><td>API client</td><td><span className="admin-status is-warning">Medium · 68</span></td><td>18 min ago</td><td><button className="admin-button is-quiet">Review</button></td></tr></tbody></table></div></section></>;
}

