import { Activity, AlertTriangle, Database, LockKeyhole, ShieldCheck } from 'lucide-react';

import { formatInteger } from '../../admin/adminUtils';
import useAdminData from '../../admin/useAdminData';
import ActivityTimeline from '../../components/admin/ActivityTimeline';
import { AdminEmpty, AdminError, AdminLoading } from '../../components/admin/AdminDataState';
import AdminPageHeader, { downloadReport } from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';
import { adminService } from '../../services/adminService';

export default function AdminSecurityPage() {
	const { data, loading, error, reload } = useAdminData(adminService.getSecurity, { ranged:false }); const header = <AdminPageHeader eyebrow="Intelligence" title="Security monitoring" description="Security state observable from Vault sessions, rate limits, and admin audit records." showRange={false} exportName={data ? 'vaultchain-security' : undefined} onExport={() => downloadReport('vaultchain-security', data?.events || [])}/>;
	if (error) return <>{header}<AdminError message={error} onRetry={reload}/></>; if (loading || !data) return <>{header}<AdminLoading/></>;
	const { summary, health, events, controls, riskySessions } = data;
	return <>{header}<div className="admin-stats-grid"><StatCard label="Security score" value={`${summary.securityScore} / 100`} detail="Derived from blocked and review states" icon={ShieldCheck} tone="green"/><StatCard label="Currently blocked" value={formatInteger(summary.blockedThreats)} detail="Vault unlock rate limits" icon={LockKeyhole} tone="red"/><StatCard label="Active Vault sessions" value={formatInteger(summary.activeSessions)} detail="Unexpired unlock grants" icon={Activity} tone="blue"/><StatCard label="Accounts under review" value={formatInteger(summary.riskyAccounts)} detail="User status marked review" icon={AlertTriangle} tone="amber"/></div><div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Recent security events" description="Failed Vault unlocks and privileged access changes">{events.length ? <ActivityTimeline items={events}/> : <AdminEmpty title="No security events recorded"/>}</AnalyticsCard><AnalyticsCard title="Security controls" description="Implemented controls only"><div className="admin-control-list">{controls.map((control) => <article key={control.name}><span>{control.status === 'Active' ? <ShieldCheck size={16}/> : <AlertTriangle size={16}/>}</span><div><strong>{control.name}</strong><p>{control.detail}</p></div><b className={control.status === 'Active' ? '' : 'is-warning'}>{control.status}</b></article>)}</div><div className="admin-health-list"><div><span>Database</span><strong>{health.database}</strong></div><div><span>Query latency</span><strong>{health.databaseLatencyMs} ms</strong></div><div><span>Process uptime</span><strong>{formatInteger(health.processUptimeSeconds)} sec</strong></div></div></AnalyticsCard></div><section className="admin-card admin-risk-table"><header><div><h2>Risky sessions</h2><p>Requires stored IP, device, location, and session-risk telemetry</p></div><Database size={18}/></header>{riskySessions.length ? <div/> : <AdminEmpty title="Session telemetry is not collected" description="VaultChain currently stores only token fingerprints and expiry times, so it cannot honestly display device or location rows."/>}</section></>;
}
