import { Check, LockKeyhole, Save, Settings2 } from 'lucide-react';
import { useEffect, useState } from 'react';

import AdminPageHeader from '../../components/admin/AdminPageHeader';
import { adminService } from '../../services/adminService';

export default function AdminSettingsPage() {
	const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const [fee, setFee] = useState('5.00');
	useEffect(() => { adminService.getSettings().then((settings) => { const rate = settings.marketplace_commission_rate?.value; if (rate !== undefined) setFee((Number(rate) * 100).toFixed(2)); }).catch(() => {}); }, []);
	async function save(event) { event.preventDefault(); setError(''); try { await adminService.updateCommission(Number(fee)); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } catch (saveError) { setError(saveError.message); } }
	return <><AdminPageHeader eyebrow="System" title="Platform settings" description="Configure marketplace economics, operational thresholds, and administrator policies."/>{error ? <div className="error-banner">{error}</div> : null}<div className="admin-settings-grid"><form className="admin-card admin-settings-form" onSubmit={save}><header><span><Settings2 size={18}/></span><div><h2>Marketplace configuration</h2><p>Global commercial settings applied to new transactions.</p></div></header><div className="admin-settings-fields"><label><span>Marketplace commission</span><p>Percentage retained from every successful sale.</p><div><input type="number" min="0" max="20" step="0.1" value={fee} onChange={(event) => setFee(event.target.value)}/><b>%</b></div></label><label><span>Minimum listing price</span><p>Lowest allowed marketplace sale value.</p><div><b>$</b><input type="number" defaultValue="10.00"/></div></label><label><span>Seller payout hold</span><p>Fraud-prevention delay before funds become available.</p><select defaultValue="24 hours"><option>Instant</option><option>24 hours</option><option>48 hours</option><option>7 days</option></select></label><label className="admin-toggle-setting"><div><span>Automatic suspicious listing freeze</span><p>Pause listings scoring below the confidence threshold.</p></div><input type="checkbox" defaultChecked/></label></div><footer><button className="admin-button" type="submit">{saved ? <Check size={15}/> : <Save size={15}/>} {saved ? 'Changes saved' : 'Save changes'}</button></footer></form><section className="admin-card admin-settings-form"><header><span><LockKeyhole size={18}/></span><div><h2>Admin security policy</h2><p>Access controls for privileged accounts.</p></div></header><div className="admin-settings-fields"><label className="admin-toggle-setting"><div><span>Require multi-factor authentication</span><p>All admin roles must use a second factor.</p></div><input type="checkbox" defaultChecked/></label><label className="admin-toggle-setting"><div><span>Log sensitive data exports</span><p>Record the administrator and reason for each export.</p></div><input type="checkbox" defaultChecked/></label><label><span>Session timeout</span><p>Automatically sign admins out after inactivity.</p><select defaultValue="30 minutes"><option>15 minutes</option><option>30 minutes</option><option>1 hour</option><option>4 hours</option></select></label><label><span>Audit log retention</span><p>Minimum duration for immutable activity records.</p><select defaultValue="365 days"><option>90 days</option><option>180 days</option><option>365 days</option><option>Indefinite</option></select></label></div></section></div></>;
}
