import { AlertTriangle, ArrowRight, BadgeDollarSign, CheckCircle2, CircleDollarSign, FileCheck2, Images, ShoppingBag, UsersRound } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link } from 'react-router-dom';

import { formatChange, formatInteger, formatMoney, formatPercent, mapTransaction } from '../../admin/adminUtils';
import useAdminData from '../../admin/useAdminData';
import ActivityTimeline from '../../components/admin/ActivityTimeline';
import { AdminEmpty, AdminError, AdminLoading } from '../../components/admin/AdminDataState';
import AdminPageHeader, { downloadReport } from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';
import TransactionTable from '../../components/admin/TransactionTable';
import { useAuth } from '../../context/AuthContext';
import { adminService } from '../../services/adminService';

export default function AdminDashboardPage() {
	const { user } = useAuth(); const { range, setRange, data, loading, error, reload } = useAdminData(adminService.getOverview);
	const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; const name = user?.fullName?.split(' ')[0] || 'Admin';
	if (error) return <><AdminPageHeader eyebrow="Platform overview" title={`${greeting}, ${name}`} description="Live operational and marketplace data." range={range} onRangeChange={setRange}/><AdminError message={error} onRetry={reload}/></>;
	if (loading || !data) return <><AdminPageHeader eyebrow="Platform overview" title={`${greeting}, ${name}`} description="Live operational and marketplace data." range={range} onRangeChange={setRange}/><AdminLoading/></>;
	const { totals, period, changes, trend, health } = data; const recent = data.recentTransactions.map(mapTransaction); const fee = Number(data.commissionRate || 0); const exampleFee = 1000 * fee / 100; const sources = period.marketplaceRevenue ? [{ name: 'Marketplace commission', value: 100, color: '#635bff' }] : [];
	const overviewExport = [
		{ metric:'Total users', value:totals.users }, { metric:'New users', value:period.newUsers },
		{ metric:'Total assets', value:totals.assets }, { metric:'New assets', value:period.newAssets },
		{ metric:'Verified assets', value:totals.verifiedAssets }, { metric:'Completed transactions', value:period.transactions },
		{ metric:'Gross marketplace volume', value:period.grossVolume }, { metric:'Marketplace commission revenue', value:period.marketplaceRevenue },
	];
	return <><AdminPageHeader eyebrow="Platform overview" title={`${greeting}, ${name}`} description="Live operational and marketplace data." exportName="vaultchain-platform-overview" onExport={() => downloadReport('vaultchain-platform-overview', overviewExport)} range={range} onRangeChange={setRange} updatedAt={new Date()}/>
		<div className="admin-stats-grid is-five"><StatCard label="Total users" value={formatInteger(totals.users)} change={formatChange(changes.users)} detail={`${formatInteger(period.newUsers)} joined in this period`} icon={UsersRound}/><StatCard label="Registered assets" value={formatInteger(totals.assets)} change={formatChange(changes.assets)} detail={`${formatInteger(period.newAssets)} added in this period`} icon={Images} tone="blue" delay={.05}/><StatCard label="Verified assets" value={formatInteger(totals.verifiedAssets)} detail={`${formatPercent(totals.verificationRate)} verification coverage`} icon={FileCheck2} tone="green" delay={.1}/><StatCard label="Marketplace revenue" value={formatMoney(period.marketplaceRevenue)} change={formatChange(changes.revenue)} detail="Commission in selected period" icon={CircleDollarSign} tone="amber" inverse delay={.15}/><StatCard label="Transactions" value={formatInteger(period.transactions)} change={formatChange(changes.transactions)} detail="Completed sales in selected period" icon={ShoppingBag} tone="cyan" delay={.2}/></div>
		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Revenue growth" description="Recorded commission revenue in the selected period" action={<Link className="admin-inline-link" to="/admin/revenue">View report <ArrowRight size={13}/></Link>}><div className="admin-chart-total"><strong>{formatMoney(period.marketplaceRevenue)}</strong><span><b>{formatChange(changes.revenue)}</b> vs previous equal period</span></div>{trend.some((point) => point.revenue) ? <ResponsiveContainer width="100%" height={285}><AreaChart data={trend}><defs><linearGradient id="dashboardRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--admin-accent)" stopOpacity={.28}/><stop offset="1" stopColor="var(--admin-accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis tickFormatter={(value) => formatMoney(value)} axisLine={false} tickLine={false}/><Tooltip formatter={(value) => formatMoney(value)}/><Area type="monotone" dataKey="revenue" stroke="var(--admin-accent)" strokeWidth={2.5} fill="url(#dashboardRevenue)"/></AreaChart></ResponsiveContainer> : <AdminEmpty title="No commission revenue" description="Completed marketplace sales in this period will populate this chart."/>}</AnalyticsCard><AnalyticsCard title="Revenue sources" description="Sources recorded by the current revenue ledger">{sources.length ? <><div className="admin-donut"><ResponsiveContainer width="100%" height={215}><PieChart><Pie data={sources} dataKey="value" innerRadius={63} outerRadius={83} paddingAngle={3} stroke="none">{sources.map((item) => <Cell key={item.name} fill={item.color}/>)}</Pie></PieChart></ResponsiveContainer><div><strong>100%</strong><span>Revenue</span></div></div><div className="admin-source-list"><div><span><i style={{ background:'#635bff' }}/>Marketplace commission</span><strong>{formatMoney(period.marketplaceRevenue)}</strong></div></div></> : <AdminEmpty title="No revenue sources yet" description="VaultChain currently records marketplace commission only."/>}</AnalyticsCard></div>
		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Transaction volume" description="Completed marketplace sales">{trend.some((point) => point.transactions) ? <ResponsiveContainer width="100%" height={250}><BarChart data={trend}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="transactions" fill="var(--admin-accent)" radius={[5,5,0,0]} maxBarSize={38}/></BarChart></ResponsiveContainer> : <AdminEmpty title="No completed transactions"/>}</AnalyticsCard><AnalyticsCard title="Platform health" description="Measured from current application state"><div className="admin-health-score"><div><strong>{health.database === 'operational' ? 'Operational' : 'Unavailable'}</strong><span>Database</span></div><CheckCircle2 size={23}/></div><div className="admin-health-list"><div><span>Database query latency</span><strong>{health.databaseLatencyMs} ms</strong></div><div><span>API process uptime</span><strong>{formatInteger(health.processUptimeSeconds)} sec</strong></div><div><span>Verification queue</span><strong>{formatInteger(health.verificationQueue)}</strong></div><div><span>Payment success</span><strong>{formatPercent(health.paymentSuccess)}</strong></div><div><span>Accounts under review</span><strong className="is-warning">{formatInteger(health.flaggedAccounts)}</strong></div></div></AnalyticsCard></div>
		<AnalyticsCard title="Recent transactions" description="Latest marketplace commission activity" action={<Link className="admin-inline-link" to="/admin/transactions">View all <ArrowRight size={13}/></Link>}>{recent.length ? <TransactionTable rows={recent} compact/> : <AdminEmpty title="No transactions in this period"/>}</AnalyticsCard>
		<div className="admin-dashboard-grid admin-bottom-grid"><AnalyticsCard className="is-wide" title="Security activity" description="Recorded Vault and administrative access signals" action={data.securityEvents.length ? <span className="admin-alert-count"><AlertTriangle size={13}/>{data.securityEvents.length} recorded</span> : null}>{data.securityEvents.length ? <ActivityTimeline items={data.securityEvents}/> : <AdminEmpty title="No security events recorded" description="Failed Vault unlocks and privileged access changes will appear here."/>}</AnalyticsCard><section className="admin-commission-card"><header><span><BadgeDollarSign size={19}/></span><b>Primary revenue model</b></header><h2>Marketplace transaction commission</h2><p>The configured fee is loaded from platform settings and applied atomically to successful sales.</p><div className="admin-commission-flow"><div><small>Buyer pays</small><strong>{formatMoney(1000)}</strong></div><ArrowRight size={16}/><div className="is-accent"><small>VaultChain fee ({fee.toFixed(2)}%)</small><strong>{formatMoney(exampleFee)}</strong></div><ArrowRight size={16}/><div><small>Seller receives</small><strong>{formatMoney(1000-exampleFee)}</strong></div></div><Link to="/admin/revenue">Explore revenue analytics <ArrowRight size={13}/></Link></section></div>
	</>;
}
