import { ArrowRight, BadgeDollarSign, CircleDollarSign, Clock3, RotateCcw } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useNavigate } from 'react-router-dom';

import { formatChange, formatInteger, formatMoney, mapTransaction } from '../../admin/adminUtils';
import useAdminData from '../../admin/useAdminData';
import { AdminEmpty, AdminError, AdminLoading } from '../../components/admin/AdminDataState';
import AdminPageHeader, { downloadReport } from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import RevenueChart from '../../components/admin/RevenueChart';
import StatCard from '../../components/admin/StatCard';
import TransactionTable from '../../components/admin/TransactionTable';
import { useAuth } from '../../context/AuthContext';
import { adminService } from '../../services/adminService';

export default function AdminRevenuePage() {
	const navigate = useNavigate(); const { user } = useAuth(); const { range, setRange, data, loading, error, reload } = useAdminData(adminService.getRevenue);
	const header = <AdminPageHeader eyebrow="Finance" title="Revenue analytics" description="Revenue from persisted marketplace transactions." range={range} onRangeChange={setRange} exportName={data ? 'vaultchain-revenue' : undefined} onExport={() => downloadReport('vaultchain-revenue', data?.transactions || [])}/>;
	if (error) return <>{header}<AdminError message={error} onRetry={reload}/></>; if (loading || !data) return <>{header}<AdminLoading/></>;
	const { summary, changes, sources, trend } = data; const recent = data.transactions.map(mapTransaction); const fee = summary.commissionRate; const exampleFee = fee * 10;
	return <>{header}<div className="admin-stats-grid"><StatCard label="Total revenue" value={formatMoney(summary.totalRevenue)} change={formatChange(changes.revenue)} detail="Net recorded platform earnings" icon={CircleDollarSign}/><StatCard label="Marketplace fees" value={formatMoney(summary.marketplaceFees)} detail={`${formatInteger(summary.completedTransactions)} completed sales`} icon={BadgeDollarSign} tone="green"/><StatCard label="Pending commission" value={formatMoney(summary.pendingPayments)} detail="From pending transactions" icon={Clock3} tone="amber"/><StatCard label="Refunded commission" value={formatMoney(summary.refunds)} detail="From refunded transactions" icon={RotateCcw} tone="red"/></div>
		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Revenue growth" description="Commission by selected time bucket">{trend.some((point) => point.revenue) ? <RevenueChart data={trend}/> : <AdminEmpty title="No revenue in this period"/>}</AnalyticsCard><AnalyticsCard title="Revenue source distribution" description="Only sources backed by the revenue ledger are shown">{sources.length ? <><div className="admin-donut"><ResponsiveContainer width="100%" height={205}><PieChart><Pie data={sources} dataKey="amount" nameKey="name" innerRadius={58} outerRadius={80} stroke="none"><Cell fill="var(--admin-accent)"/></Pie><Tooltip formatter={(value) => formatMoney(value)}/></PieChart></ResponsiveContainer><div><strong>{formatMoney(summary.totalRevenue)}</strong><span>Total</span></div></div><div className="admin-source-list">{sources.map((source) => <div key={source.name}><span><i style={{ background:'var(--admin-accent)' }}/>{source.name}</span><strong>{source.percentage}%</strong></div>)}</div></> : <AdminEmpty title="No revenue sources recorded"/>}</AnalyticsCard></div>
		<div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Marketplace transactions" description="Completed sales per time bucket">{trend.some((point) => point.transactions) ? <ResponsiveContainer width="100%" height={275}><BarChart data={trend}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="transactions" fill="var(--admin-accent)" radius={[5,5,0,0]} maxBarSize={42}/></BarChart></ResponsiveContainer> : <AdminEmpty title="No transactions in this period"/>}</AnalyticsCard><section className="admin-card admin-fee-card"><header><div><span>Commission model</span><strong>{fee.toFixed(2)}%</strong></div><BadgeDollarSign size={24}/></header><div className="admin-fee-example"><p>Calculated from current setting</p><div><span>Gross sale</span><strong>{formatMoney(1000)}</strong></div><div className="is-fee"><span>Platform commission</span><strong>− {formatMoney(exampleFee)}</strong></div><div><span>Seller payout</span><strong>{formatMoney(1000-exampleFee)}</strong></div></div>{String(user?.role).toUpperCase() === 'SUPER_ADMIN' ? <button className="admin-button is-secondary" type="button" onClick={() => navigate('/admin/settings')}>View fee configuration <ArrowRight size={14}/></button> : null}</section></div>
		<AnalyticsCard title="Recent revenue activity" description="Commission captured from completed sales">{recent.length ? <TransactionTable rows={recent} compact/> : <AdminEmpty title="No revenue activity"/>}</AnalyticsCard></>;
}
