import { AlertTriangle, Ban, Copy, ScanSearch } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import AdminPageHeader from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';

const success = [{ month: 'Jan', rate: 94 }, { month: 'Feb', rate: 96 }, { month: 'Mar', rate: 98 }, { month: 'Apr', rate: 97.4 }, { month: 'May', rate: 98.2 }, { month: 'Jun', rate: 98.6 }];
const confidence = [{ range: '<80%', count: 112 }, { range: '80–90%', count: 480 }, { range: '90–95%', count: 1640 }, { range: '95–100%', count: 4870 }];

export default function AdminVerificationPage() {
	return <><AdminPageHeader eyebrow="Trust & safety" title="Verification analytics" description="Monitor AI accuracy, confidence, suspicious matches, and manual review queues." exportName="vaultchain-verification"/><div className="admin-stats-grid"><StatCard label="Verifications today" value="6,482" change="14.6%" detail="98.6% completed" icon={ScanSearch}/><StatCard label="Duplicate detections" value="245" change="-4.1%" detail="Flagged for review" icon={Copy} tone="amber"/><StatCard label="Fraud attempts" value="32" change="-11.2%" detail="All automatically blocked" icon={AlertTriangle} tone="red"/><StatCard label="Rejected assets" value="18" change="-8.0%" detail="0.28% rejection rate" icon={Ban} tone="blue"/></div><div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Verification success rate" description="Successful authenticity checks by month"><ResponsiveContainer width="100%" height={300}><LineChart data={success}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis domain={[90, 100]} tickFormatter={(value) => `${value}%`} axisLine={false} tickLine={false}/><Tooltip formatter={(value) => `${value}%`}/><Line type="monotone" dataKey="rate" stroke="var(--success)" strokeWidth={2.5} dot={{ fill: 'var(--surface)', strokeWidth: 2 }}/></LineChart></ResponsiveContainer></AnalyticsCard><AnalyticsCard title="AI model health" description="Live accuracy signals"><div className="admin-model-score"><strong>97.8%</strong><span>Overall accuracy</span><i><b style={{ width: '97.8%' }}/></i></div><div className="admin-health-list"><div><span>False positive rate</span><strong>0.8%</strong></div><div><span>Human agreement</span><strong>96.4%</strong></div><div><span>Median processing</span><strong>2.4 sec</strong></div><div><span>Model version</span><strong>VC Vision 4.2</strong></div></div></AnalyticsCard></div><AnalyticsCard title="AI confidence distribution" description="Verification results grouped by confidence score"><ResponsiveContainer width="100%" height={290}><BarChart data={confidence}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="range" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip cursor={{ fill: 'var(--surface-hover)' }}/><Bar dataKey="count" fill="var(--admin-accent)" radius={[6,6,0,0]} maxBarSize={70}/></BarChart></ResponsiveContainer></AnalyticsCard></>;
}

