import { Ban, CheckCircle2, Copy, ScanSearch } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import { formatInteger, formatPercent } from '../../admin/adminUtils';
import useAdminData from '../../admin/useAdminData';
import { AdminEmpty, AdminError, AdminLoading } from '../../components/admin/AdminDataState';
import AdminPageHeader, { downloadReport } from '../../components/admin/AdminPageHeader';
import AnalyticsCard from '../../components/admin/AnalyticsCard';
import StatCard from '../../components/admin/StatCard';
import { adminService } from '../../services/adminService';

export default function AdminVerificationPage() {
	const { range, setRange, data, loading, error, reload } = useAdminData(adminService.getVerification); const header = <AdminPageHeader eyebrow="Trust & safety" title="Verification analytics" description="Computed from persisted verification reports and fingerprint evidence." range={range} onRangeChange={setRange} exportName={data ? 'vaultchain-verification' : undefined} onExport={() => downloadReport('vaultchain-verification', data?.trend || [])}/>;
	if (error) return <>{header}<AdminError message={error} onRetry={reload}/></>; if (loading || !data) return <>{header}<AdminLoading/></>;
	const { summary, trend, confidence } = data; const successRate = summary.total ? summary.successful / summary.total * 100 : 0;
	return <>{header}<div className="admin-stats-grid"><StatCard label="Verification reports" value={formatInteger(summary.total)} detail="Created in selected period" icon={ScanSearch}/><StatCard label="Processed successfully" value={formatInteger(summary.successful)} detail={`${formatPercent(successRate)} processing success`} icon={CheckCircle2} tone="green" delay={.05}/><StatCard label="Exact duplicates" value={formatInteger(summary.duplicates)} detail="SHA-256 matches" icon={Copy} tone="amber" delay={.1}/><StatCard label="Rejected reports" value={formatInteger(summary.rejected)} detail="Explicitly rejected records" icon={Ban} tone="red" delay={.15}/></div><div className="admin-dashboard-grid"><AnalyticsCard className="is-wide" title="Verification processing success" description="Persisted reports not marked failed or rejected">{summary.total ? <ResponsiveContainer width="100%" height={300}><LineChart data={trend}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tickFormatter={(value) => `${value}%`} axisLine={false} tickLine={false}/><Tooltip formatter={(value) => `${value}%`}/><Line type="monotone" dataKey="rate" stroke="var(--success)" strokeWidth={2.5} dot={{ fill:'var(--surface)', strokeWidth:2 }}/></LineChart></ResponsiveContainer> : <AdminEmpty title="No verification reports"/>}</AnalyticsCard><AnalyticsCard title="Confidence coverage" description="Scores derived from stored hash evidence"><div className="admin-model-score"><strong>{formatInteger(summary.scored)}</strong><span>Reports with calculable confidence</span><i><b style={{ width: summary.total ? `${summary.scored/summary.total*100}%` : '0%' }}/></i></div><div className="admin-health-list"><div><span>Total reports</span><strong>{formatInteger(summary.total)}</strong></div><div><span>Scored reports</span><strong>{formatInteger(summary.scored)}</strong></div><div><span>Unscored reports</span><strong>{formatInteger(summary.total-summary.scored)}</strong></div><div><span>Exact hash matches</span><strong>{formatInteger(summary.duplicates)}</strong></div></div></AnalyticsCard></div><AnalyticsCard title="AI confidence distribution" description="Similarity calculated from stored SHA-256 or perceptual hash distance">{summary.scored ? <ResponsiveContainer width="100%" height={290}><BarChart data={confidence}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="range" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="count" fill="var(--admin-accent)" radius={[6,6,0,0]} maxBarSize={70}/></BarChart></ResponsiveContainer> : <AdminEmpty title="No confidence scores available" description="Reports with fingerprint comparison evidence will populate this distribution."/>}</AnalyticsCard></>;
}
